### ISSUE TITLE
Add run button in UI

### ISSUE THREAD

**Issue by bthesorceror** [influxdata/vsflux#155]
in order to properly expose run query functionality there should be a run button (play button) in the UI of vsflux when presenting a flux script

**Comment by TotallyInformation** [comment]
Better still would be to link to the "Run File" button that already exists.

**Comment by rockstar** [comment]
I agree that integrating this functionality into the "Run Code" call that already exists VSCode. That requires more work than originally estimated. If we were to create a button as a stop gap, only to take it away after The Right Way™ has been implemented, I think that would be worse than waiting to do it right.

As such, I think this needs more design and planning than originally expected.

**Comment by rockstar** [comment]
In order to implement this correctly, we'll need to build a [debugger extension](https://code.visualstudio.com/api/extension-guides/debugger-extension), which can be part of our extension, but will implement the debugger protocol. This will likely require some effort around the execution environment, e.g. is this run local, or against a server, what does the environment look like wrt to options, etc.

**Comment by rockstar** [comment]
Work tracked in #293
