### ISSUE TITLE
How can I connect influxdb v1.8 with  authentication

### ISSUE THREAD

**Issue by covered** [influxdata/vsflux#178]
vsflux ver:0.5.7

Type:InfluxDB v1
Name:xxx
Hostname and Port:

http://x.x.x.x:8086  -> Failed to connect to database
http://username:password@x.x.x.x:8086  -> Failed to connect to database

There is no way set :
--header 'Authorization: Token username:password'    
or  set a Token.

**Comment by Yuvashkenazi** [comment]
I believe I have the same problem as you. I got around this by disabling authentication (auth-enabled = false) in the influxdb.conf file, and restarting my influxd instance. Obviously not a long-term solution, adding username and password fields for the new connection screen would be nice.

**Comment by scbrickley** [comment]
Thanks for bringing this to our attention. Seems like this was an oversight on our part. We will begin work on a fix soon.

**Comment by ampujl** [comment]
I have same problem

**Comment by Sleepy-GH** [comment]
Any updates on this by any chance?

**Comment by wsgomes** [comment]
@Yuvashkenazi Is there any update on this?
I think I have this same issue since I'm trying to connect to InfluxCloud service which is still InfluxDB v1.
However, this may be an UI issue since the Test and Save button don't work when trying to add a new connection.
Is there a way to add a new connection not using this UI?
![image](https://user-images.githubusercontent.com/2425134/123292874-da4ed500-d4e9-11eb-865f-a92f071b673f.png)

**Comment by Yuvashkenazi** [comment]
@wsgomes Sorry, no update. My team has moved to v2.0 since my original comment.
