### ISSUE TITLE
Schema Browser does not show the whole schema

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/vsflux#228]
In this example, all of the measurements in the plantbuddy bucket have the exact same schema, but the schema is only displayed for the last one in the list. 

![Screen Shot 2021-05-28 at 3 59 14 PM](https://user-images.githubusercontent.com/13948193/120036128-a73e2200-bfcd-11eb-9317-c9e9eaaba117.png)

**Comment by rockstar** [comment]
This UI is a very thin wrapper around the results of this query:

```
import "influxdata/influxdb/v1"
v1.measurementTagKeys(bucket:"${bucket}", measurement: "${measurement}")
```

There is no filtering or error handling in the case of broken iterations. I can't reproduce this with any data that I can make up, and the plant buddy data has since been reaped from this account. I _suspect_ that if this issue still exists, it's an issue with `v1.measurementTagKeys`, but I can't confirm that. I have no idea what else it could be on the `vsflux` side.

If we encounter this again, please feel free to re-open.
