### ISSUE TITLE
Use a wasm binary for the debug adapter

### ISSUE THREAD

**Issue by rockstar** [influxdata/vsflux#312]
The "run" functionality for flux is currently implemented as a node-based debug adapter. We should spike and implement that debug adapter as a wasm binary the way the lsp is implemented.

DOD:
  - The "run" functionality is provided by a wasm binary written in rust.

**Comment by Marwes** [comment]
So the code being debugged is really executed external right (via `Run Query`) so there isn't a lot of code that would be translated over right now (just returning a json message back I think?). So what is the plan to further expand this via wasm (rather than continuing to expand the typescript code)? Since the interpreter is in go we can't just embed that to run and debug locally so I assume any additional debugging support would still have to be executed remotely.

**Comment by rockstar** [comment]
We're going to focus our attention on the debugger experience before prioritizing the WASM adapter.
