### ISSUE TITLE
Could not get InfluxDB 2.x api handler for 1.x instance

### ISSUE THREAD

**Issue by kbfifi** [influxdata/vsflux#344]
flux extension v0.6.9
InfluxDB 1.8.10

Configured connection with InfluxDB v1. test ran ok.
Trying to use this extension with simple flux script and get this: "Could not get InfluxDB 2.x api handler for 1.x instance"

Any idea what's wrong? No V1 support? Why is it looking for V2 API for 1.x instance?

**Comment by willw-git** [comment]
I have a variation of the same problem:

Using InfluxDB 1.8.3
Platform Window 10
VS Code 1.63.2

Flux extension: Various - see below

flux extension v0.6.13
Could not get past connection screen. No response to Test or Save buttons. No obvious indication of any error.
I eventually found - by clicking on error on Flux extension in extension list window - a popup window which repeated "Could not get InfluxDB 2.x api handler for 1.x instance" error about 20 times.

Downgraded to flux extension v0.6.0, at a venture
The connection screen seemed to work and made a new connection, but the Influx window went into spasms, and produced a list of 0's instead of the buckets,

Tried flux extension v0.6.3
This lists the buckets correctly on the extension! It even let me execute a query! Staying put for the time being.
