### ISSUE TITLE
separate port number from hostname in influxdb connection config

### ISSUE THREAD

**Issue by immykins** [influxdata/vsflux#92]
Break these fields into two separate fields.

The port number field should be considered optional. If empty, we should assume port 9999. A user should be prevented from entering an invalid port number.

**Comment by kelwang** [comment]
I don't think it's a good idea, because 9999 is only for local influxdb. Influx cloud 2 is using 443, not 9999. for example: https://us-west-2-1.aws.cloud2.influxdata.com. 


We could however, giving a list of influxdb v2 connections, with all the cloud 2 urls. so user may select and choose their own.

https://us-central1-1.gcp.cloud2.influxdata.com
https://us-west-2-1.aws.cloud2.influxdata.com
https://eu-central-1-1.aws.cloud2.influxdata.com
https://127.0.0.1:9999

**Comment by kelwang** [comment]
add reference of https://github.com/influxdata/vsflux/issues/101

**Comment by kelwang** [comment]
close this one in favor of #101

**Comment by jademcgough** [comment]
Reopening this. If a user is running their instance on a non-standard port, there's no way to configure it.
